name: Add Project
description: Add a Flutter project to the list
title: "[Add] <owner/repo>"
labels: ["review-needed"]
assignees: []

body:
  - type: markdown
    attributes:
      value: "<!--FORM-->"

  - type: input
    id: repo_url
    attributes:
      label: Repository URL
      placeholder: "https://github.com/owner/repo"
    validations:
      required: true
      pattern: "^https://github\\.com/[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+/?$"

  - type: input
    id: project_name
    attributes:
      label: Project Name
      placeholder: "MyAwesomeProject"
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - App
        - Package
        - Plugin
        - Sample
        - Tools & Infra
        - Uncategorized
    validations:
      required: true

  - type: textarea
    id: short_description
    attributes:
      label: Short description
      description: "Up to ~120 chars"
      placeholder: "What does this project do?"
      render: text
    validations:
      required: true

  - type: textarea
    id: tags
    attributes:
      label: Tags
      placeholder: "Mobile, Networking(Dio)"
      render: text
    validations:
      required: true

  - type: input
    id: license
    attributes:
      label: License
      placeholder: "MIT / Apache-2.0 / BSD-3-Clause ..."
    validations:
      required: false
      
  - type: markdown
    attributes:
      value: "</!--FORM-->"
